---
apiVersion: v2
name: sefaria-dafchat
version: v0.0.1

icon: https://raw.githubusercontent.com/Sefaria/Sefaria-Project/e757b59968adbc0d6845eaa1b420f934ad864d32/static/img/logo/icon.svg
home: https://sefaria.org
sources:
  - https://github.com/Sefaria/dafChat
...
