apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.deployEnv }}
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
spec:
  tls:
    - secretName: {{ template "sefaria.secrets.originTls" . }}
    {{- if ( template "sefaria.secrets.originIlTls" . ) }}
    - secretName: {{ template "sefaria.secrets.originIlTls" . }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .serviceName | default "nginx" }}-{{ $.Values.deployEnv }}
                port:
                  number: {{ .port | default "80" }}
    {{- end }}
