apiVersion: v1
kind: ConfigMap
metadata:
  name: braintrust-tag-and-push-script-{{ .Values.deployEnv }}
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
data:
  braintrust_tag_and_push.py: |
{{ .Files.Get "scripts/scheduled/braintrust_tag_and_push.py" | indent 4 }}
