name: Release to Production
on:
  workflow_dispatch:
    inputs:
      chart_version:
        type: string
        required: true
        default: current
        description: Set to 'current' to use currently deployed chart version or '0.x.y' to specify chart

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.release-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/npm@9.0.2
            @semantic-release/github@8.0.7
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check version was generated
        id: releaseVersion
        run: |
          if [[ -z "${{ steps.semantic.outputs.new_release_version }}" ]]; then
            if [[ -z "$(git tag --points-at HEAD -l 'v*')" ]]; then
              echo "No release version available"
              exit 1
            else
            echo "releaseVersion=$(git tag --points-at HEAD -l 'v*')" >> $GITHUB_OUTPUT
            fi
          else
            echo "releaseVersion=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_OUTPUT
          fi
      - name: "Version Info:"
        run: echo "${{ steps.releaseVersion.outputs.releaseVersion }}"
  deploy:
    needs: semantic-release
    uses: ./.github/workflows/production-deploy.yaml
    secrets: inherit
    with:
      version: ${{ needs.semantic-release.outputs.version }}
      chart_version: ${{ inputs.chart_version }}
